apiVersion: v1
kind: Service
metadata:
  annotations:
    version: 1.0.0
  labels:
    io.service: loki
  name: loki
spec:
  ports:
    - name: "3100"
      port: 3100
      targetPort: 3100
  selector:
    io.service: loki
status:
  loadBalancer: {}
