apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    version: 1.0.0
  labels:
    io.service: loki
  name: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      io.service: loki
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        version: 1.0.0
      labels:
        io.service: loki
    spec:
      containers:
        - args:
            - -config.file=/etc/loki/loki.yml
          image: grafana/loki:latest
          name: loki
          ports:
            - containerPort: 3100
          resources: {}
          volumeMounts:
            - name: loki-config
              mountPath: /etc/loki
      hostname: loki
      restartPolicy: Always
      volumes:
      - name: loki-config
        configMap:
          name: loki-config
          items:
          - key: loki.yml
            path: loki.yml
status: {}
