# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - main
  paths:
    include:
      - grafana

jobs:
- deployment: Grafana
  displayName: Deploy Grafana
  environment: k8smonitoring
  pool:
    name: Pool
  strategy: 
    runOnce:
      deploy:
        steps:
        - checkout: self
        - task: Kubernetes@1
          inputs:
            connectionType: 'Kubernetes Service Connection'
            kubernetesServiceEndpoint: 'cb-monitoring'
            namespace: 'cb-monitoring'
            command: 'login'
          displayName: Login to AKS

        #- task: Kubernetes@1
        #  inputs:
        #    connectionType: 'Kubernetes Service Connection'
        #    kubernetesServiceEndpoint: 'cb-monitoring'
        #    namespace: 'cb-monitoring'
        #    command: 'apply'
        #    arguments: '-f grafana/grafana-configmap.yml'
        #    secretType: 'dockerRegistry'
        #    containerRegistryType: 'Azure Container Registry'
        #  displayName: Update grafana config

        - task: Kubernetes@1
          inputs:
            connectionType: 'Kubernetes Service Connection'
            kubernetesServiceEndpoint: 'cb-monitoring'
            namespace: 'cb-monitoring'
            command: 'apply'
            arguments: '-f  grafana/grafana-deployment.yml -f grafana/grafana-service.yml -f grafana/grafana-ingress.yml'
            secretType: 'dockerRegistry'
            containerRegistryType: 'Azure Container Registry'
          displayName: Update grafana deployment, service and ingress

        - task: Kubernetes@1
          inputs:
            command: 'logout'
          displayName: Logout of AKS
          condition: Always()
          