# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - main
  paths:
    include:
      - prom2teams

jobs:
- deployment: prom2teams
  displayName: Deploy prom2teams
  environment: k8smonitoring
  pool:
    name: Pool
  strategy: 
    runOnce:
      deploy:
        steps:
        - checkout: self
        - task: Kubernetes@1
          inputs:
            connectionType: 'Kubernetes Service Connection'
            kubernetesServiceEndpoint: 'cb-monitoring'
            namespace: 'cb-monitoring'
            command: 'login'
          displayName: Login to AKS


        - task: Kubernetes@1
          inputs:
            connectionType: 'Kubernetes Service Connection'
            kubernetesServiceEndpoint: 'cb-monitoring'
            namespace: 'cb-monitoring'
            command: 'apply'
            arguments: '-f  prom2teams/prom2teams-deployment.yml -f prom2teams/prom2teams-service.yml -f prom2teams/prom2teams-ingress.yml'
            secretType: 'dockerRegistry'
            containerRegistryType: 'Azure Container Registry'
          displayName: Update prom2teams deployment, service and ingress

        - task: Kubernetes@1
          inputs:
            command: 'logout'
          displayName: Logout of AKS
          condition: Always()