- include_vars: variables/monitoring_vars.yml

- name: Setting path for infra
  set_fact:
    stPath: "{{builddir}}/{{scrapetarget_loc}}/infra"
  when: job_name == "node_exporter" 

- name: create directories if doesnt exist
  delegate_to: localhost
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{builddir}}/{{scrapetarget_loc}}/app"
    - "{{builddir}}/{{scrapetarget_loc}}/infra"


- name: create jsonfile
  delegate_to: localhost
  file:
    path: "{{stPath}}/{{profile_name}}-{{job_name}}.json"
    state: touch
- name: Add contents for individual exporter
  local_action: 'lineinfile line="[ "  path={{stPath}}/{{profile_name}}-{{job_name}}.json'


- name: update the configuration for generic
  delegate_to: localhost
  blockinfile:
    path: "{{stPath}}/{{profile_name}}-{{job_name}}.json"
    marker: " "
    block: |3 
           {
           "targets": [
           "{{inventory_hostname}}:{{job_port}}"
             ],
            "labels": {
            "job": "{{job_name}}",
            "hostid": "{{profile_name}}-{{machine_ip}}",
            "{{custom_labels | replace('-','" : "') | replace(',','" , "') | lower }}",
            "hostip": "{{machine_ip}}"
            }
            },
  when: custom_labels.find('NA') == -1
- name: update the configuration for generic without custom labels
  delegate_to: localhost
  blockinfile:
    path: "{{stPath}}/{{profile_name}}-{{job_name}}.json"
    marker: " "
    block: |3 
           {
           "targets": [
           "{{inventory_hostname}}:{{job_port}}"
             ],
            "labels": {
            "job": "{{job_name}}",
            "hostid": "{{profile_name}}-{{machine_ip}}",
            "hostip": "{{machine_ip}}"
            }
            },
  when: custom_labels.find('NA') != -1   


