apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-yml
data:
  blackbox.yml: |-
    modules:
      http_2xx:
        prober: http
        timeout: 5s
        http:
          method: GET
          no_follow_redirects: false
          fail_if_ssl: false
          fail_if_not_ssl: false
          tls_config:
            insecure_skip_verify: true

